apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhtap-tas
  janus-idp.io/tekton: rhtap-tas
  backstage.io/kubernetes-id: rhtap-tas
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap-tas
resources: 
- deployment.yaml
- route.yaml
- service.yaml
